name: ğŸ§ª Build and test
on:
  push:
    branches:
      - '**'
      - '!release'
      - '!main'
      - '!feature/**'
      - '!wip/**'
      - '!bugfix/**'

jobs:

  build:
    name: ğŸ— Build
    runs-on: ubuntu-latest

    steps:
      - name: GIT checkout
        uses: actions/checkout@v2

      - name: Set up Java 16
        uses: actions/setup-java@v1
        with:
          java-version: '16'

      - name: Set up Maven
        uses: navikt/bidrag-maven/setup@v7.0.5
        with:
          repositories: maven-central=https://repo.maven.apache.org/maven2,github-packages=https://maven.pkg.github.com/navikt/maven-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test with Maven
        run: |
          mvn install -B -e
